res.partner:   
     
     Name: "Partner"  
     Fields: 
     - 'id'
     - 'name'
     - 'phone'
     - 'mobile'
     images:
     - 'image_1920'
product.product:   
       
     Name: "Partner"  
     Fields: 
      - 'id'
      - 'name'  
product.category:
      Fields:
      - 'id'
      - 'name'
product.template:
      Fields:
      - 'id'
      - 'name'
      - 'categ_id'
      - 'product_variant_count'
      images:
      - 'image_1920'
stock.warehouse:
     Fields:
      - 'id'
      - 'name'
ir.module.category:
      Fields:
      - 'id'
      - 'name'
      - 'description'
      -  'parent_id'
      - 'module_ids'
ir.module.module:
      Fields:
      - 'id'
      - 'name'
      - 'description'
      - 'category_id'
ir.actions.report:
      Fields:
      - 'id'
      - 'name'
ir.ui.view:
 Fields:
      - 'id'
      - 'name'    
ir.model: 
      Fields:
      - 'id'
      - 'name'     
      - 'info'
      - 'modules'
      - 'view_ids'
      - 'field_id'